kind: VirtualClusterInstance
apiVersion: management.loft.sh/v1
metadata:
  name: vcluster-deployed-with-flux
  namespace: p-auth-core
spec:
  displayName: vCluster Deployed with Flux
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    access:
      defaultClusterRole: view
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        name: vcluster
        repo: https://loft-demos.github.io/vcluster-charts
        version: 0.22.3
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          coredns:
            enabled: true
            embedded: true
          backingStore:
            etcd:
              embedded:
                enabled: true
          statefulSet:
            image:
              repository: "loft-demos/vcluster-pro"
              tag: "0.22.4-k8s.v1.31.6"
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
      apps:
        - name: generate-vcluster-kubeconfig
      objects: |-
        ---
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        metadata:
          name: podinfo
        spec:
          interval: 12h
          url: https://stefanprodan.github.io/podinfo
        ---
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: podinfo
        spec:
          targetNamespace: podinfo
          storageNamespace: podinfo
          releaseName: podinfo
          kubeConfig:
            secretRef:
              name: vc-vcluster-deployed-with-flux
              key: config
          chart:
            spec:
              chart: podinfo
              sourceRef:
                kind: HelmRepository
                name: podinfo
          interval: 50m
          driftDetection:
            mode: enabled
            ignore:
              - paths: ["/spec/replicas"]
                target:
                  kind: Deployment
          install:
            remediation:
              retries: 3
          # Default values
          # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
          values:
            ui:
              message: "deployed to vcluster-deployed-with-flux test-2"
            ingress:
              enabled: true
              className: nginx
              hosts:
                - host: podinfo-vcluster-deployed-with-flux-juliet.us.demo.dev
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
  clusterRef:
    cluster: loft-cluster
  access:
    - name: instance-access
      verbs:
        - create
        - use
        - get
      subresources:
        - logs
        - kubeconfig
      teams:
        - auth-core
        - loft-admins
  networkPeer: true
