apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: vcluster-with-clusterref-ns
  namespace: p-default
spec:
  template:
    helmRelease:
      chart:
        version: 0.23.0-alpha.6
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          coredns:
            enabled: true
            embedded: true
    pro:
      enabled: true
  clusterRef:
    cluster: loft-cluster
    namespace: test
  owner:
    user: kurtmadel
