apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-env-config
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev
    - clusters:
        selector:
          matchLabels:
            env: qa
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: juliet-app-{{name}}
    spec:
      destination:
        namespace: juliet-app-{{metadata.labels.env}}
        server: '{{server}}'
      info:
        - name: GitHub Repo
          value: https://github.com/loft-demos/juliet-app/
      project: default
      source:
        path: k8s-manifests/{{metadata.labels.env}}/
        repoURL: https://github.com/loft-demos/juliet-app.git
        targetRevision: main
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
