apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-instance
  namespace: p-auth-core
spec:
  ignoreDifferences:
    - group: storage.loft.sh
      kind: VirtualClusterInstance
      jsonPointers:
        - /spec
        - /status
        - /metadata
  interval: 5m
  targetNamespace: p-auth-core
  sourceRef:
    kind: GitRepository
    name: juliet-app
  path: "./vcluster-gitops/argocd/flux/kustomize"
  prune: true
  timeout: 2m
  patches:
    - target:
        kind: VirtualClusterInstance
        group: storage.loft.sh
      patch: |-
        - op: add
          path: /metadata/annotations/kustomize.toolkit.fluxcd.io/reconcile
          value: disabled
