name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: kubepi-test
    steps:
    - run: echo "Meg is awesome 🎉 This job uses runner scale set runners!"
    - run: sleep 60
    - run: echo "Done"
